### ISSUE TITLE
Rahmenbedingungen und Teilnehmer eingeben/ändern/löschen - Standard

### ISSUE THREAD

**Issue by ToniMur** [haevg-rz/MentorSpeedDatingApp#1]
Als Organisator des Speeddatings möchte ich folgende Daten

- [x] initial eingeben

- [x] speichern und

- [x] nach dem ersten Speichern ändern können:

- Überschrift
- Mentorinnen: Titel, Vorname, Name (Anzahl kann variieren)
- Mentees: Titel, Vorname, Name (Anzahl kann variieren)
(Mentorinnen und Mentees müssen jeweils einzeln änderbar/löschbar sein.)

- Start-Uhrzeit: ab welcher Uhrzeit starten die Speed-Datings an dem Tag
- Ende-Uhrzeit: zu welcher Uhrzeit sind die Speed-Datings an dem Tag beendet

- [x] Bei Öffnen der Anwendung werden schon einmal früher gespeicherte Daten initial angezeigt.

- [x] Als Organisator möchte ich alle Mentees auf einmal löschen können.

- [x] Als Organisator möchte ich alle eingegebenen Daten auf einmal löschen können.

Ergänzung nach Austausch mit Entwicklern:
Es wird ein zentraler Datensatz gespeichert, der bei erneutem Speichern überschrieben wird. Der Datensatz wird beim Öffnen der App angezeigt.

Beispiele:
- Überschrift: Kennenlerntag Mentorinnen/Mentees 20.02.2020 in Franfurt
- Mentorinnen:
-- Dr. Maximiliane Mustermann
-- Prof. Dr. Sonja Müller
- Mentees:
-- Dr. Donalda Duck
-- Birgit Maja
- Start-Uhrzeit: 10:30 Uhr
- Ende-Uhrzeit: 17:00 Uhr

**Comment by enricopau** [comment]
To-Do: 
- Abfrage ob ungespeicherte Änderungen beim Schließen
- Löschen der jeweiligen Zeile anhand jeweils eines Buttons

**Comment by enricopau** [comment]
To-

- CanExecute nur == true, wenn alle TimeValidationRules == true

**Comment by KirillSerebryakov123** [comment]
> To-Do:
> 
> * CanExecute nur == true, wenn alle TimeValidationRules == true

Sollte ergänzt werden zu den bereits vorhandenen Abfragen

**Comment by enricopau** [comment]
Speichern funktionert nicht
