### ISSUE TITLE
Speed-Dating-Planung erstellen

### ISSUE THREAD

**Issue by ToniMur** [haevg-rz/MentorSpeedDatingApp#2]
[Beispiel Speeddating.xlsx](https://github.com/haevg-rz/MentorSpeedDatingApp/files/4166080/Beispiel.Speeddating.xlsx)

Als Organisator des Speeddatings möchte ich folgendes Ergebnis auf meinem Bildschirm erhalten, wenn ich die Speed-Dating-Planung erstelle (siehe auch Beispieldatei):

- [x] Es wird eine Matrix erzeugt.

Auf der einen Achse sind die Mentorinnen, auf der anderen die Zeitintervalle für ein "Date" (Ein Date ist eine Paarung aus jeweils einer Mentorin und einer Mentee). In den Zellen der Matrix stehen die Namen der Mentees.

- [x] Jede Mentorin soll genau ein Date mit einer Mentee haben.
- [x] Das Zeitintervall wird dynamisch berechnet. Es ergibt sich aus dem Gesamtzeitraum für das Speeddating, der Anzahl Dates, die zeitlich nacheinander stattfinden müssen, und den Pausen.

- [x] Eine Mentorin soll höchstens 2 Stunden ohne Pause daten. Eine Mentee soll höchstens 2 Stunden ohne Pause daten. Es können mehrere Pausen hintereinander liegen. Zum Anfang und zum Ende des Speeddating-Zeitraums können Pausen liegen.

**Comment by enricopau** [comment]
Aus Besprechung (21.04.2020)
Mindestdauer: 10 Minuten
Maximaldauer: 30 Minuten
Pausen nach 120 Minuten: erstmal optional geworden
Bei Grenzfällen, in denen die Matchings nicht in die Zeiten passen, soll eine Meldung ausgegeben werden und später die Möglichkeit zur Anpassung gegeben werden.

**Comment by ToniMur** [comment]
Die Generierung der Matching-Tabelle klappt bereits sehr gut! Mir ist noch eine Kleinigkeit im Test aufgefallen:
Wenn ich (aus Versehen) bei der Eingabe eine Leerzeile für Mentorin/Mentee eingebe, wird diese in die Matching-Tabelle mit aufgenommen.
![IMG_0949](https://user-images.githubusercontent.com/60462580/89262449-e7dc4180-d62f-11ea-8e60-f6c86fef3a3a.jpg)
![IMG_0950](https://user-images.githubusercontent.com/60462580/89262458-ec085f00-d62f-11ea-9750-332ad0fa2fec.jpg)
