### ISSUE TITLE
Vorschlag für eine überarbeitete GUI

### ISSUE THREAD

**Issue by dhcgn** [haevg-rz/MentorSpeedDatingApp#22]
Die aktuelle GUI enthält eine willkürliche Anordnung von Buttons, eine klare visuelle Aufteilung wäre hier bestimmt vom Vorteil und bringt ein "modernes" Feeling in die Anwendung.

Die Vorschlägen skizzieren die Idee wo es hingehen könnte, für Aktionen am Grid wird ein Kontextmenü verwendet.

Freue mich über Feedback!

# IST

![image](https://user-images.githubusercontent.com/6566207/82992609-ab70e180-9fff-11ea-845e-3610aad6f9d0.png)

# Vorschlag 1

![image](https://user-images.githubusercontent.com/6566207/82992664-bfb4de80-9fff-11ea-91c7-1f9f65167929.png)

# Vorschlag 2

![image](https://user-images.githubusercontent.com/6566207/82992685-c80d1980-9fff-11ea-81a8-930c7b0b7696.png)

**Comment by enricopau** [comment]
Navigation Menu in Sidebar implemented
