### ISSUE TITLE
Review 27.05.2020

### ISSUE THREAD

**Issue by dhcgn** [haevg-rz/MentorSpeedDatingApp#23]
- [x] Unused PrintMatchingCommand in MainWindow
https://github.com/haevg-rz/MentorSpeedDatingApp/blob/c712e37f15b81c3c906d015936cbc91de5bb49c0/MentorSpeedDatingApp/Views/MainWindow.xaml#L203
- [x] Using styles for DataGrid in MainWindow
https://github.com/haevg-rz/MentorSpeedDatingApp/blob/c712e37f15b81c3c906d015936cbc91de5bb49c0/MentorSpeedDatingApp/Views/MainWindow.xaml#L103-L118
- [x] Avoid dynamic in MatchingViewModel
https://github.com/haevg-rz/MentorSpeedDatingApp/blob/c712e37f15b81c3c906d015936cbc91de5bb49c0/MentorSpeedDatingApp/ViewModel/MatchingViewModel.cs#L21
- [x] Not 'blendable' MatchingWindow
- [x] Why build a DataGridTextColumn and not using a style?
https://github.com/haevg-rz/MentorSpeedDatingApp/blob/c712e37f15b81c3c906d015936cbc91de5bb49c0/MentorSpeedDatingApp/ExtraFunctions/DataGridCreator.cs#L15
- [x] How should this work in production?
https://github.com/haevg-rz/MentorSpeedDatingApp/blob/c712e37f15b81c3c906d015936cbc91de5bb49c0/MentorSpeedDatingApp/ViewModel/MainViewModel.cs#L223
- [x] Why JsonConvert.DeserializeAnonymousType?
https://github.com/haevg-rz/MentorSpeedDatingApp/blob/c712e37f15b81c3c906d015936cbc91de5bb49c0/MentorSpeedDatingApp/ViewModel/MainViewModel.cs#L245
- [ ] TimeSlotCalculator must be under test coverage

### remarks

1. Git Feature Branch Workflow anwende, also je Feature ein Branch
1. No CD
1. No CanExecutes

**Comment by enricopau** [comment]
Why JsonConvert.DeserializeAnonymousType?
- "definition" ist ein anonymous type

**Comment by enricopau** [comment]
How should this work in production?
- Saves to and loads from AppData/Local/MSDAPP/savedData.json in Production
