### ISSUE TITLE
Review-29.07.2020

### ISSUE THREAD

**Issue by enricopau** [haevg-rz/MentorSpeedDatingApp#27]
- [x]  Umbrüche für längere Namen

- [x]  Uhrzeittabelle soll auch Endzeit des Dates mit anzeigen (z.B.: 8:00 - 8:45)

- [ ]  Die Previews sollen plattformunabhängig released werden

- [x]  Testdaten um (jeweils bis zu 12) Mentorinnen und Mentees erweitern.

**Comment by dhcgn** [comment]
- [] dotnet publish mit rid auf win-x64 (nicht win10-x64) und zippen
- [] Speichern stürzt ab
- [] Resizeable der GUI
- [] Hint Text bei ComboBox
- [] Tagesplan bei mehrere Mentorinnen bildschirmfüllend anzeigen
- [] Release Pipeline
