### ISSUE TITLE
Speed-Dating-Planung drucken

### ISSUE THREAD

**Issue by ToniMur** [haevg-rz/MentorSpeedDatingApp#3]
- [x] Als Organisator des Speed-Datings möchte ich die Matrix mit allen Mentees, Mentorinnen und Zeitintervallen drucken können.

- [x] Der Ausdruck soll auf einem Blatt im Querformat abgebildet werden.

- [x] Das Layout entspricht weitgehend der Beispieldatei. Wegen der Corporate Identity ist eine hellgrüne Farbe zu bevorzugen.
[Beispiel Speeddating.xlsx](https://github.com/haevg-rz/MentorSpeedDatingApp/files/4169394/Beispiel.Speeddating.xlsx)

Ergänzung nach Austausch mit Entwicklern:
Das Drucken wird über die Windows-Funktionalität realisiert. Das Matching wird also zunächst im temp-Ordner in einer Datei gespeichert, Format .xlsx
Die gespeicherte Datei wird direkt nach dem Speichern in einem neuen Fenster geöffnet und der User kann den Druck starten.

**Comment by enricopau** [comment]
Drucken muss explizit im Matching-Ausgabe-Fenster erfolgen. Die aktuelle Implementierung lässt sich dort dann implementieren mit wenigen Handgriffen.

**Comment by enricopau** [comment]
Mit commit fceaafb87959d8884dd6ea6aa35582e11c20de41reviewfertig.
