### ISSUE TITLE
Aufwandseinschätzung: Tabellensteuerung

### ISSUE THREAD

**Issue by enricopau** [haevg-rz/MentorSpeedDatingApp#32]
- [ ]  Mit "Enter" in eine neue Zeile springen

- [ ]  Mit Tab **konsistent** eine Spalte weiter springen

**Comment by ToniMur** [comment]
Befüllen der Mentorinnen- oder Mentee-Tabelle:
- Startposition des Cursors ist die Spalte "Vorname"
- TAB springt zur nächsten Spalte (beim Feld "Vorname" also in "Nachname"), kein Zeilenwechsel mit TAB möglich (steht der Cursor in der Spalte "Name" und wird TAB gedrückt passiert nichts)
- ENTER beginnt eine neue Zeile in der Spalte "Vorname"; wird ENTER in einer Zeile gedrückt und die Spalte "Nachname" ist nicht gefüllt wird kein Zeilenwechsel ermöglicht

**Comment by enricopau** [comment]
> * Startposition des Cursors ist die Spalte "Vorname"

Nicht die Spalte "Titel", da diese ja die erste Spalte der Tabelle ist?

**Comment by ToniMur** [comment]
Genau. Das war ja eine Anregung von euch, dass das bei der Eingabe sehr umständlich ist. Es gibt zwar einige, die einen Titel führen, aber die meisten werden ohne Titel erfasst.
