### ISSUE TITLE
Start- und Endzeit als Dropdown

### ISSUE THREAD

**Issue by enricopau** [haevg-rz/MentorSpeedDatingApp#33]
- [x]  Startzeit und Endzeit sind als Dropdown Menü abgebildet

**Comment by ToniMur** [comment]
- Stunden und Minuten sind optisch in einem Feld zusammengefasst, können aber noch getrennt eingegeben werden.
- Der User kann zwischen DropDown und Freitexteingabe der Uhrzeit wählen.
- Bei Freitexteingabe: Wenn der User Stunden eingegeben hat springt der Cursor automatisch zu Minuten.

**Comment by ToniMur** [comment]
Ich hatte zum Logo noch Ideen:
- Das Paar Mentorin/Mentee wird später als Tandem bezeichnet, daher könnte man ein grünes Tandem auf weißem Hintergrund als Logo verwenden.
- Zwei sich ineinander fügende Puzzle-Stücke.

**Comment by enricopau** [comment]
> * Stunden und Minuten sind optisch in einem Feld zusammengefasst, können aber noch getrennt eingegeben werden.
> * Der User kann zwischen DropDown und Freitexteingabe der Uhrzeit wählen.
> * Bei Freitexteingabe: Wenn der User Stunden eingegeben hat springt der Cursor automatisch zu Minuten.

Kannst du uns hier vielleicht mal ein visuelles Beispiel raussuchen, wie du dir das genau vorstellst?

**Comment by ToniMur** [comment]
Auf [bahn.de](www.bahn.de) sieht es so aus:
<img width="192" alt="image" src="https://user-images.githubusercontent.com/60462580/90221978-752b4d00-de0b-11ea-97f4-780cd9f0df35.png">
Die Pfeile können aber durch ein anderes GUI-Element mit der Funktion für das Ändern der Uhrzeit in Zeitintervallen ersetzt werden.

**Comment by ToniMur** [comment]
Hier noch ein [Beispiel:](https://www.koeln-bonn-airport.de/fluege/abflug-ankunft.html)
<img width="197" alt="image" src="https://user-images.githubusercontent.com/60462580/90222375-3a75e480-de0c-11ea-8997-a0f4a811e3e7.png">
Das passt für mich auch gut mit einer Ausnahme: wenn ich auf die Stunden klicke, kommt ein weiteres Auswahlfeld für die Stunden. Da hätte ich lieber, dass der Cursor im Stundenfeld bleibt und ich Freitext eingeben kann.

**Comment by enricopau** [comment]
Wie besprochen ist die aktuelle Version mit Dropdowns annehmbar. 
Wenn weitere Wünsche umgesetzt werden sollen, kann dieses Issue wieder eröffnet werden.
