### ISSUE TITLE
Rahmenbedingungen und Teilnehmer eingeben/ändern/löschen - Ausnahme NoGo-Date

### ISSUE THREAD

**Issue by ToniMur** [haevg-rz/MentorSpeedDatingApp#4]
Als Organisator des Speed-Datings möchte ich mehrere sog. NoGo-Dates

- [x] anlegen

- [x] ändern

- [x] löschen
können.
Ein NoGo-Date ist eine Paarung aus Mentorin und Mentee, die **NICHT** stattfinden darf.

Beispiel
Mentorinnen 1,2,3
Mentees A,B,C

NoGo-Date 2 mit C
No Go-Date 3 mit A

Zu planende Dates:
1A, 1B, 1C
2A, 2B
3B, 3C

**Comment by enricopau** [comment]
@ToniMur @dhcgn Wir würden gerne an einer Lösung arbeiten, die NoGoDates umzusetzen und die zeitliche Integrität (sprich nicht zu viele Pausen) beizubehalten, würden aber erstmal eine Lösung programmieren, in der die Mentor X Mentee Kombination, die ein NoGoDate ist, durch eine Pause ersetzt wird.

@ToniMur wie häufig wird diese Feature voraussichtlich in Anspruch genommen?

**Comment by ToniMur** [comment]
Hallo Enrico, hallo Team,

Der Lösungsvorschlag mit der zusätzlichen Pause ist gut, das könnt ihr so machen. Das Feature wird 1-2 Mal in Anspruch genommen, d.h. wir haben ein bis zwei Mentor/Mentee-Kombinationen, die ein NoGoDate sind.

Viele Grüße
Monika
