### ISSUE TITLE
Showstopper: Eingegebene Liste von Teilnehmern verschwindet

### ISSUE THREAD

**Issue by ToniMur** [haevg-rz/MentorSpeedDatingApp#40]
Bei der Eingabe der Liste der Mentorinnen habe ich zunehmend Eingabeschwierigkeiten mit Enter gehabt. Teilweise wurde keine neue Zeile erstellt. Erst wenn ich mit Tab das Feld aktiviert hatte, konnte ich mit Enter eine neue Zeile erstellen.
Nach ein paar dieser Schwierigkeiten war plötzlich die Liste komplett weg- siehe Screenshot.
Info: ich hatte das Fenster mit der Matching-Tabelle parallel während der Änderungen geöffnet.
Unter dem Screenshot geht's weiter mit der Fehlerbeschreibung ;-)

![image](https://user-images.githubusercontent.com/60462580/91664735-67571680-eaf1-11ea-9a62-d23682f13265.png)

Ich habe die Anwendung geschlossen, bei der Frage nach dem Verwerfen der Änderungen/Rückkehr in die Anwendung habe ich auf OK (Verwerfen) geklickt. Dann habe ich die Anwendung neu gestartet. Die Liste der Mentorinnen war wieder vollständig da - es ist also ein Anzeigeproblem:
![image](https://user-images.githubusercontent.com/60462580/91664853-1d226500-eaf2-11ea-9ae9-81037bb0b396.png)

Bei der Liste der Mentees ist mir dasselbe passiert - die Liste verschwand in der Ansicht bei der Eingabe und dem Versuch, in eine neue Zeile zu springen. Ich habe dann nach Auftreten des Fehlers gespeichert, das hat nicht geklappt. Jetzt kann ich die gespeicherte Datei zwar aufrufen, aber keine Mentees mehr eingeben:
![image](https://user-images.githubusercontent.com/60462580/91665168-f7965b00-eaf3-11ea-8555-378c4d52a89d.png)

**Comment by ToniMur** [comment]
... und wie ich gerade feststelle hilft es auch nicht, die json-Datei zu löschen:
![image](https://user-images.githubusercontent.com/60462580/91665527-8ad09000-eaf6-11ea-95ee-c8049872316f.png)

**Comment by KirillSerebryakov123** [comment]
Das Verschwinden der Liste hat wohl damit zu tun, dass du mit Tab auf den Button "Mentees löschen" (oder "Mentoren löschen") gekommen bist und dann Enter gedrückt hast. Dies ist aber ein Bug und sollte behoben werden (Enrico hat es behoben aber beim Mergen habe ich es vermutlich kaputt gemacht). Man kann auf den Tabellen mit Rechtsklick ein Kontextmenü aufrufen und damit einen Mentor/Mentee hinzufügen.

**Comment by KirillSerebryakov123** [comment]
Die ursprünglich angeforderte Steuerung (mit Tab Spalten weiter springen aber kein Zeilenwechsel, mit Enter in die Nächste Zeile UND die Spalte Vorname) lässt sich leider nicht umsetzen. Es ist viel zu aufwändig und leider sehr Fehleranfällig. Die Möglichkeit einen neun Eintrag anzulegen (über die leere Zeile "NewItemPlaceholder") hat manchmal auch Fehler verursacht, weshalb diese Entfernt wurde. Ein neuer Eintrag wird entweder automatisch oder manuell hinzugefügt durch/wenn:
1) Man in der letzten Zeile der jeweiligen Tabelle ist und der Vorname und Nachname nicht leer sind und man Enter/Tab drückt
2) Rechtsklick auf die Tabelle -> neun Mentor/Mentee hinzufügen

**Comment by KirillSerebryakov123** [comment]
Gemäß der Besprechung vom 31.08.2020 Umgesetzt
