### ISSUE TITLE
Ausdruck Matching-Tabelle unvollständig

### ISSUE THREAD

**Issue by ToniMur** [haevg-rz/MentorSpeedDatingApp#41]
Ich habe eine Liste mit 20 Mentorinnen und 3 Mentees.
Beim Druck der Matching-Tabelle erscheint in der ANSICHT für jede Mentorin in der Liste eine Spalte.
Der tatsächliche AUSDRUCK enthält nur eine Teilmenge der Mentorinnen (nein, es gab keine 2. Seite ;-)):

![image](https://user-images.githubusercontent.com/60462580/91665406-9c656800-eaf5-11ea-9570-2449eac51b38.png)

**Comment by enricopau** [comment]
Der Ausdruck kann jetzt anhand von mehreren Fenstern gesteuert werden. 
Dabei wird die Tabelle in Größen geteilt,  die sinnvoll für ein DINA4 Druckformat sind. Diese werden dann in einzelnen Fenstern ausgegeben, die dann individuell gedruckt werden können.

**Comment by ToniMur** [comment]
Beim Drucken mit je 20 Mentorinnen und Mentees kommt der Hinweis auf mehrere Fenster im Hintergrund beim Drucken. Ich sehe dann ein Druckfenster, das sich nach ein paar Sekunden schließt und auch die gesamte Anwendung wird beendet:

![image](https://user-images.githubusercontent.com/60462580/92129252-90361f00-ee03-11ea-8d0b-0ba32e9a5355.png)

Endansicht:
![image](https://user-images.githubusercontent.com/60462580/92129368-b52a9200-ee03-11ea-9751-63db4883437e.png)

**Comment by enricopau** [comment]
Habe einen Fix eingebaut. Kann den Fehler erstmal nicht reproduzieren, würde das aber gerne weiter testen bevor ich das Issue schließe.

**Comment by ToniMur** [comment]
Bei mir ist es auch nur einmal passiert, das andere Mal hat es geklappt...

**Comment by enricopau** [comment]
Kann dieses Issue geschlossen werden?
