### ISSUE TITLE
Vorausfüllen des Namens der gespeicherten Datei falls vorhanden

### ISSUE THREAD

**Issue by ToniMur** [haevg-rz/MentorSpeedDatingApp#43]
Solange wie nur eine Datei wieder geöffnet werden kann, sollte bei Vorhandensein einer gespeicherten Datei ihr Dateiname im Speichern-Dialog vorausgefüllt sein, damit der User nicht unter dem Namen "savedData" abspeichert.
Im gezeigten Beispiel wäre der Dateiname "Kennenlerntag" im Feld von "savedData" enthalten:

![image](https://user-images.githubusercontent.com/60462580/92129715-2bc78f80-ee04-11ea-8a62-166f9b38dd10.png)

**Comment by enricopau** [comment]
Zuletzt genutzter Dateiname und Ordner wird mitgespeichert und abgerufen bei Aufrufen von Speichern.
