### ISSUE TITLE
Prio 2: Mehrere Fenster beim Drucken erscheinen auch wenn nicht nötig

### ISSUE THREAD

**Issue by ToniMur** [haevg-rz/MentorSpeedDatingApp#45]
Bei jeweils 10 Mentorinnen und Mentees erscheint beim Drucken das Hinweisfenster, dass die Anzahl zu groß für eine Druckseite sei. Es öffnen sich zwei Fenster, im Hauptfenster kann ich den Button "Drucken" klicken.
Im Ausdruck sind aber alle Mentorinnen und Mentees auf einer Druckseite enthalten.

Fenster 1:
![image](https://user-images.githubusercontent.com/60462580/92134362-b78fea80-ee09-11ea-831e-8700485d44b6.png)

Fenster 2: (Hinweis auf Export ist gut! "Seite 0" klingt komisch - muss das nicht Seite 2 sein?
![image](https://user-images.githubusercontent.com/60462580/92134404-c4acd980-ee09-11ea-9ca0-2e8413558884.png)

Druckseite (schlechte Qualität kommt vom Scannen:
![image](https://user-images.githubusercontent.com/60462580/92134842-4dc41080-ee0a-11ea-94a4-913c1820833b.png)

**Comment by enricopau** [comment]
Die "optimale" Druckansicht ist aktuell auf 8 Spalten eingestellt, weil es eine gute Größe für den Ausdruck ergibt. 
Eventuell könnte man eine Option dafür einbauen, ab welcher Spaltenanzahl man die Druckansicht aufbricht...

**Comment by enricopau** [comment]
Schließung nach Absprache im Review
