### ISSUE TITLE
Dauer der Dates sind minutengenau

### ISSUE THREAD

**Issue by ToniMur** [haevg-rz/MentorSpeedDatingApp#46]
Die Dauer der Dates umfasst z.B. 22 oder 23 Minuten. Das ist für die Durchführung des Kennenlerntages eine zu genaue Zeiteinteilung. Wir benötigen stattdessen 5-Minuten-genaue Date-Dauern.

Zum Beispiel:
9:00-9:15 Uhr
9:00-9:20 Uhr
9:00-9:25 Uhr
9:00-9:35 Uhr
etc.

**Comment by enricopau** [comment]
Dies ist kein Bug, sondern die Art wie der Algorithmus funktioniert. Können das aber als neue Mindestanforderung aufnehmen.

**Comment by ToniMur** [comment]
Ja stimmt. Das ist eine astreine Spezifikationslücke - mein Fehler also. So ist der Algorithmus nicht praxistauglich, daher müssen wir das hochpriorisiert ändern.

**Comment by enricopau** [comment]
Closed after Fix #50
