### ISSUE TITLE
Überschrift auf Ausdruck aufnehmen

### ISSUE THREAD

**Issue by ToniMur** [haevg-rz/MentorSpeedDatingApp#47]
Der im Feld "Überschrift" im Eingabefenster hinterlegte Text erscheint oben auf dem Ausdruck der Matching-Tabelle (so wie im Druckfenster bereits richtig umgesetzt). Bei mehreren Druckseiten erscheint die Überschrift auf jeder Seite.

**Comment by enricopau** [comment]
Die Überschrift wird nun mit in den Druck integriert. 
Wenn keine Überschrift gewählt wird ist "Kennenlerntag YEAR" der Standard.
Die Seitenanzahlen, die in den Fenstern angezeigt werden, werden vor dem Druck herausgefiltert.
